"""Pydantic models for every published data shape.

These are the single source of truth for both:
  - runtime construction in transform.py / build_manifest.py / securities/registry.py
  - JSON Schema files committed under schemas/ (generated by pipeline.schemas)

`extra="forbid"` is set on every model so downstream consumers can rely
on the schema as exhaustive: an unknown key is drift, not flexibility.

Field aliases (`3mo`, `1yr`, …) are used where Python identifiers can't
match the wire shape; serialize with `model_dump(by_alias=True)`.
"""

from __future__ import annotations

from typing import Annotated, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Schema version constants. Bump in lockstep with the corresponding builder.
# ---------------------------------------------------------------------------

FUND_SNAPSHOT_SCHEMA_VERSION = "0.5"
FUNDS_MANIFEST_SCHEMA_VERSION = "1"
SECURITY_SCHEMA_VERSION = "0.1"


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)


# ---------------------------------------------------------------------------
# Shared building blocks
# ---------------------------------------------------------------------------

class PeriodBucket(_Strict):
    """Time-bucketed risk metric (DV01, DV100, credit spread). All-null is
    valid; the parent decides whether to emit the bucket at all."""
    p3mo: Annotated[Optional[float], Field(alias="3mo", default=None)]
    p1yr: Annotated[Optional[float], Field(alias="1yr", default=None)]
    p5yr: Annotated[Optional[float], Field(alias="5yr", default=None)]
    p10yr: Annotated[Optional[float], Field(alias="10yr", default=None)]
    p30yr: Annotated[Optional[float], Field(alias="30yr", default=None)]


# ---------------------------------------------------------------------------
# Fund snapshot — the per-quarter portfolio file
# ---------------------------------------------------------------------------

class DebtBlock(_Strict):
    maturity_date: Optional[str] = None
    coupon_kind: Optional[str] = None
    coupon_rate: Optional[float] = None
    is_default: bool = False
    interest_payments_in_arrears: bool = False
    is_mandatory_convertible: bool = False
    is_contingent_convertible: bool = False


class Holding(_Strict):
    ticker: Optional[str] = None
    isin: Optional[str] = None
    lei: Optional[str] = None
    issuer_cik: Optional[str] = None
    name: Optional[str] = None
    weight: float
    fair_value_usd: Optional[float] = None
    balance: Optional[float] = None
    units: Optional[str] = None
    asset_category: Optional[str] = None
    asset_class: Optional[str] = None
    issuer_cat: Optional[str] = None
    country: Optional[str] = None
    currency: Optional[str] = None
    payoff_profile: Optional[str] = None
    is_restricted: bool = False
    is_fair_valued: bool = False
    fair_value_level: Optional[str] = None
    debt: Optional[DebtBlock] = None


class ShareClass(_Strict):
    class_id: str
    ticker: Optional[str] = None
    name: Optional[str] = None
    expense_ratio: Optional[float] = None


class FeesSourceFiling(_Strict):
    accession_no: str
    filing_date: Optional[str] = None
    source_url: str


class MonthlyReturn(_Strict):
    month: str
    class_id: Optional[str] = None
    return_pct: float


class InterestRateRisk(_Strict):
    currency: str
    dv01: Optional[PeriodBucket] = None
    dv100: Optional[PeriodBucket] = None


class CreditSpreadRisk(_Strict):
    investment_grade: Optional[PeriodBucket] = None
    non_investment_grade: Optional[PeriodBucket] = None


class Fund(_Strict):
    name: Optional[str] = None
    series_id: str
    series_lei: Optional[str] = None
    registrant_cik: Optional[str] = None
    registrant_name: Optional[str] = None
    registrant_lei: Optional[str] = None
    as_of: str
    total_assets_usd: Optional[float] = None
    total_liabs_usd: Optional[float] = None
    net_assets_usd: Optional[float] = None
    cash_not_in_portfolio_usd: Optional[float] = None
    source_filing: str
    source_url: str
    is_final_filing: bool = False
    dropped_holdings_count: int = 0
    dropped_weight: float = 0.0
    # will revisit — expand alongside X-ray coverage badge work
    # cash_in_portfolio_weight: float = 0.0
    # categorized_weight: float = 0.0
    interest_rate_risk: list[InterestRateRisk] = Field(default_factory=list)
    credit_spread_risk: Optional[CreditSpreadRisk] = None
    monthly_returns: list[MonthlyReturn] = Field(default_factory=list)
    share_classes: list[ShareClass] = Field(default_factory=list)
    fees_source_filings: list[FeesSourceFiling] = Field(default_factory=list)


class FundSnapshot(_Strict):
    schema_version: Literal["0.5"] = FUND_SNAPSHOT_SCHEMA_VERSION
    generated_at: str
    fund: Fund
    holdings: list[Holding]


# ---------------------------------------------------------------------------
# Funds manifest — the index file at the root of fund-extracts
# ---------------------------------------------------------------------------

class FundEntry(_Strict):
    series_id: str
    name: Optional[str] = None
    registrant_cik: Optional[str] = None
    tickers: list[str] = Field(default_factory=list)
    latest_period: str
    latest_accession: Optional[str] = None


class FundsManifest(_Strict):
    schema_version: Literal["1"] = FUNDS_MANIFEST_SCHEMA_VERSION
    generated_at: str
    funds: list[FundEntry]


# ---------------------------------------------------------------------------
# Securities registry — one record per issuer CIK
# ---------------------------------------------------------------------------

class SecuritySource(_Strict):
    edgar_fetched_at: str


class Security(_Strict):
    cik: str
    name: Optional[str] = None
    sic: Optional[str] = None
    sic_description: Optional[str] = None
    sector: Optional[str] = None
    country: Optional[str] = None
    state_of_incorporation: Optional[str] = None
    tickers: list[str] = Field(default_factory=list)
    exchanges: list[str] = Field(default_factory=list)
    entity_type: Optional[str] = None
    source: SecuritySource
    schema_version: Literal["0.1"] = SECURITY_SCHEMA_VERSION
